### ISSUE TITLE
post page always show all page.

### ISSUE THREAD

**Issue by KongYian** [mJackie/Typecho-Theme-Blogecho#1]
hello,l find your theme at official website. And using it as my website theme. ths for your work.but l find my post is not like your demo page. my post always show all page.like this :http://47.94.11.157/blueYian/index.php/  because l learn html and css less. so can u help me to solve this problem

**Comment by KongYian** [comment]
btw....l sovle ```add  .post_t {
	margin:15px 0 15px 0;
	overflow: hidden;
	height: 250px;
}```  so your blog's style is not as the same as github HEAD?

**Comment by mJackie** [comment]
Its always show all text of the article. Because you forget add the `<!--more-->` tag to control how much too show in the index.
